name: mediquick_client
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  toast: ^0.1.5
  path_provider:
  url_launcher: ^5.0.3
  firebase_core: "0.7.0"
  http:
  device_info: ^2.0.2

  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
